/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NitRouteImport } from './routes/nit'
import { Route as CsaRouteImport } from './routes/csa'
import { Route as IndexRouteImport } from './routes/index'

const NitRoute = NitRouteImport.update({
  id: '/nit',
  path: '/nit',
  getParentRoute: () => rootRouteImport,
} as any)
const CsaRoute = CsaRouteImport.update({
  id: '/csa',
  path: '/csa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csa': typeof CsaRoute
  '/nit': typeof NitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csa': typeof CsaRoute
  '/nit': typeof NitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csa': typeof CsaRoute
  '/nit': typeof NitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/csa' | '/nit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/csa' | '/nit'
  id: '__root__' | '/' | '/csa' | '/nit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CsaRoute: typeof CsaRoute
  NitRoute: typeof NitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nit': {
      id: '/nit'
      path: '/nit'
      fullPath: '/nit'
      preLoaderRoute: typeof NitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csa': {
      id: '/csa'
      path: '/csa'
      fullPath: '/csa'
      preLoaderRoute: typeof CsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CsaRoute: CsaRoute,
  NitRoute: NitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
